// districts.js
export const data = [
  {
    districtName: "Srikakulam",
    constituencies: [
      "Ichchapuram(1)",
      "Palasa(2)",
      "Tekkali(3)",
      "Pathapatnam(4)",
      "Srikakulam(5)",
      "Amadalavalasa(6)",
      "Etcherla(7)",
      "Narasannapeta(8)",
    ],
  },
  {
    districtName: "Vizianagaram",
    constituencies: [
      "Rajam(9)",
      "Bobbili(14)",
      "Cheepurupalli(15)",
      "Gajapathinagaram(16)",
      "Nellimarla(17)",
      "Vizianagaram(18)",
    ],
  },
  {
    districtName: "Araku",
    constituencies: [
      /*************  ✨ Codeium Command 🌟  *************/
      "Palakonda (ST)(10)",
      "Kurupam (ST)(11)",
      "Parvathipuram (SC)12",
      "Salur (ST)(13)",
      "Araku Valley (ST)(28)",
      "Paderu (ST)(29)",
      "Rampachodavaram (ST)(53)",
    ],
  },
  {
    districtName: "Visakhapatnam",
    constituencies: [
      /*************  ✨ Codeium Command 🌟  *************/
      "Srungavarapukota(19)",
      "Bhimili(20)",
      "Visakhapatnam East(21)",
      "Visakhapatnam South(22)",
      "Visakhapatnam North(23)",
      "Visakhapatnam West(24)",
      "Gajuwaka(25)",
    ],
  },
  {
    districtName: "Anakapalli",
    constituencies: [
      "Chodavaram (26)",
      "Madugula (27)",
      "Anakapalle (30)",
      "Pendurthi (31)",
      "ELAMANCHILI (32)",
      "Payakaraopet (SC) (33)",
      "Narsipatnam (34)",
    ],
  },
  {
    districtName: "Kakinada",
    constituencies: [
      "Tuni (35)",
      "Prathipadu (36)",
      "Pithapuram (37)",
      "Kakinada Rural (38)",
      "Peddapuram (39)",
      "Kakinada City (41)",
      "Jaggampeta (52)",
    ],
  },
  {
    districtName: "Amalapuram",
    constituencies: [
      "Ramachandrapuram (42)",
      "Mummidivaram (43)",
      "Amalapuram (SC) (44)",
      " Razole (SC) (45)",
      "Gannavaram (SC) (46)",
      " Kothapeta (47)",
      "Mandapeta (48)",
    ],
  },
  {
    districtName: "Rajahmundry",
    constituencies: [
      " Anaparthi (40)",
      "Rajanagaram (49)",
      "Rajahmundry City (50)",
      "Rajahmundry Rural (51)",
      "Kovvur (SC) (54)",
      "Nidadavole (55)",
      "Gopalapuram (SC) (66)",
    ],
  },
  {
    districtName: "Narsapuram",
    constituencies: [
      "Achanta (56)",
      " Palacole (57)",
      "Narasapuram (58)",
      " Bhimavaram (59)",
      " Undi (60)",
      " Tanuku (61)",
      " Tadepalligudem (62)",
    ],
  },
  {
    districtName: "Eluru",
    constituencies: [
      "Ungutur (63)",
      "Denduluru (64)",
      "Eluru (65)",
      "Polavaram (ST) (67)",
      "Chintalapudi (SC) (68)",
      "Nuzvid (70)",
      "Kaikalur (73)",
      
    ],
  },
  {
    districtName: "Vijayawada",
    constituencies: [
      "Tiruvuru (SC) (69)",
      "Vijayawada West (79)",
      "Vijayawada Central (80)",
      "Vijayawada East (81)",
      "Mylavaram (82)",
      "Nandigama (SC) (83)",
      "Jaggayyapeta (84)",
    ],
  },
  {
    districtName: "Machilipatnam",
    constituencies: [
      "GANNAVARAM (KRISHNA) (71)",
      "Gudivada (72)",
      "Pedana (74)",
      "Machilipatnam (75)",
      "Avanigadda (76)",
      "Pamarru (SC) (77)",
      "Penamaluru (78)",
    ],
  },
  {
    districtName: "Narasaraopet",
    constituencies: [
      "PEDDAKURAPADU (85)",
      "Chilakaluripet (96)",
      "Narasaraopet (97)",
      "Sattenapalle (98)",
      "Vinukonda (99)",
      "Gurajala (100)",
      "Macherla (101)",
    ],
  },
  {
    districtName: "Guntur",
    constituencies: [
      "Tadikonda (SC) (86)",
      "Mangalagiri (87)",
      "Ponnur (88)",
      "Tenali (91)",
      "Prathipadu (SC) (93)",
      "Guntur West (94)",
      "Guntur East (95)",
    ],
  },
  {
    districtName: "Bapatla",
    constituencies: [
      " Vemuru (SC) (89)",
      "Repalle (90)",
      "Bapatla (92)",
      "Parchur (104)",
      "Addanki (105)",
      "Chirala (106)",
      "Santhanuthalapadu (SC) (107)",
    ],
  },
  {
    districtName: "Ongole",
    constituencies: [
      "Yerragondapalem (SC) (102)",
      "Darsi (103)",
      "Ongole (108)",
      "Kondapi (SC) (110)",
      "Markapuram (111)",
      "Giddalur (112)",
      "Kanigiri (113)",
    ],
  },
  {
    districtName: "Nellore",

    constituencies: [
      "Kandukur (109)",
      "Kavali (114)",
      "Atmakur (115)",
      " Kovur (116)",
      "Nellore City (117)",
      " Nellore Rural (118)",
      " Udayagiri (123)",
    ],
  },
  {
    districtName: "Tirupati",
    constituencies: [
      "Sarvepalli (119)",
      "Gudur (SC) (120)",
      "Sullurpeta (SC) (121)",
      "Venkatagiri (122)",
      "Tirupati (167)",
      "Srikalahasti (168)",
      "Satyavedu (SC) (169)",
    ],
  },
  {
    districtName: "Kadapa",
    constituencies: [
      "Badvel (SC) (124)",
      " Kadapa (126)",
      "Pulivendula (129)",
      "Kamalapuram (130)",
      "Jammalamadugu (131)",
      "Proddatur (132)",
      "Mydukur (133)",
    ],
  },
  {
    districtName: "Rajampet",
    constituencies: [
      "Rajampet (125)",
      "Kodur (SC) (127)",
      "Rayachoti (128)",
      "Thamballapalle (162)",
      "Pileru (163)",
      "Madanapalle (164)",
      "Punganur (165)",
    ],
  },
  {
    districtName: "Nandyal",
    constituencies: [
      "Allagadda (134)",
      "Srisailam (135)",
      "Nandikotkur (SC) (136)",
      "Panyam (138)",
      "Nandyal (139)",
      "Banaganapalle (140)",
      "Dhone (141)",
    ],
  },
  {
    districtName: "Kurnool",
    constituencies: [
      " Kurnool (137)",
      "Pattikonda (142)",
      "Kodumur (SC) (143)",
      "Yemmiganur (144)",
      "Mantralayam (145)",
      "Adoni (146)",
      "Alur (147)",
    ],
  },
  {
    districtName: "Anantapur",
    constituencies: [
      "Rayadurg (148)",
      "Uravakonda (149)",
      "Guntakal (150)",
      "Tadpatri (151)",
      "Singanamala (SC) (152)",
      "Anantapur Urban (153)",
      "Kalyandurg (154)",
    ],
  },
  {
    districtName: "Hindupur",
    constituencies: [
      "Raptadu (155)",
      "Madakasira (SC) (156)",
      "Hindupur (157)",
      "Penukonda (158)",
      "Puttaparthi (159)",
      "Dharmavaram (160)",
      "Kadiri (161)",
    ],
  },
  {
    districtName: "Chittoor",
    constituencies: [
      "Chandragiri (166)",
      "Nagari (170)",
      "Gangadhara Nellore (SC) (171)",
      "Chittoor (172)",
      "Puthalapattu (SC) (173)",
      "Palamaner (174)",
      "Kuppam (175)",
    ],
  },
];
